apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
    version: v1
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
  - name: http-health
    port: 81
  selector:
    app: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: test-server
        image: zackbutcher/test-server:v0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 81
        args:
        - --server-port=80
        - --health-port=81
        - --liveness-port=81
        - --id=backend.secondary
#        # update to make the health check return unhealthy
#        - --healthy=true
#        # update to make liveness checks take longer before returning a 200
#        - --liveness-delay=0s
#        livenessProbe:
#          httpGet:
#            path: /live
#            port: 81
#          initialDelaySeconds: 5
#          periodSeconds: 5
#        readinessProbe:
#          httpGet:
#            path: /health
#            port: 81
#          initialDelaySeconds: 5
#          periodSeconds: 5